- alias: klnexus
  command: klnexus.exe .\config.ini
  enabled: true
- alias: Controller
  command: .\units\controller_eclipse\Debug\eclipse_c.exe
  enabled: false
- alias: Power Simulation
  command: not supported by cmd line
  enabled: false
