- alias: klnexus
  command: klnexus.exe .\config.ini
  enabled: true
- alias: Controller
  command: .\units\digital_controller\Debug\digital_controller.exe
  enabled: false
- alias: Power Simulation
  command: not supported by cmd line
  enabled: false
