- alias: klnexus
  command: klnexus.exe .\config.ini
  enabled: true
- alias: Controller
  command: .\units\uC_eclipse\Debug\uC_pwm_buck_controller.exe
  enabled: false
- alias: Power Simulation
  command: not supported by cmd line
  enabled: false
